version: "3.8"

services:
  crawler:
    image: esternit/crawler:latest
    container_name: crawler-mtg
    ports:
      - "8081:8081"
    networks:
      - app-network
    env_file:
      - .env
  api:
    image: esternit/apicrawler:latest
    depends_on:
      - db
    container_name: api-mtg
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    container_name: dbpg-mtg
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
